{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "DALI test failed. Error: Critical error when building pipeline:\n",
      "Error in CPU operator `nvidia.dali.fn.readers.file`,\n",
      "which was used in the pipeline definition with the following traceback:\n",
      "\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 1987, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/qizixxx/mlbook/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_64701/1014923613.py\", line 29, in <module>\n",
      "    pipe = SimpleDALIPipeline(batch_size=1, num_threads=2, device_id=0)\n",
      "  File \"/tmp/ipykernel_64701/1014923613.py\", line 19, in __init__\n",
      "    self.input = fn.readers.file(file_root=test_image_dir, random_shuffle=False)\n",
      "\n",
      "encountered:\n",
      "\n",
      "Assert on \"SizeImpl() > 0\" failed: No files found.\n",
      "C++ context: [/opt/dali/dali/operators/reader/loader/file_label_loader.h:192] \n",
      "Current pipeline object is no longer valid.\n"
     ]
    }
   ],
   "source": [
    "from nvidia.dali.pipeline import Pipeline\n",
    "import nvidia.dali.fn as fn\n",
    "import nvidia.dali.types as types\n",
    "import os\n",
    "\n",
    "# Replace with the directory containing your test image\n",
    "test_image_dir = \"q\"\n",
    "\n",
    "# Check if the directory and at least one image exist\n",
    "if not os.path.isdir(test_image_dir):\n",
    "    raise FileNotFoundError(f\"Test image directory not found: {test_image_dir}\")\n",
    "if len(os.listdir(test_image_dir)) == 0:\n",
    "    raise FileNotFoundError(f\"No images found in directory: {test_image_dir}\")\n",
    "\n",
    "# Define a simple DALI pipeline\n",
    "class SimpleDALIPipeline(Pipeline):\n",
    "    def __init__(self, batch_size, num_threads, device_id):\n",
    "        super(SimpleDALIPipeline, self).__init__(batch_size, num_threads, device_id)\n",
    "        self.input = fn.readers.file(file_root=test_image_dir, random_shuffle=False)\n",
    "        self.decode = fn.decoders.image(self.input, device=\"mixed\", output_type=types.RGB)\n",
    "        self.resize = fn.resize(self.decode, resize_x=224, resize_y=224)\n",
    "\n",
    "    def define_graph(self):\n",
    "        images = self.resize\n",
    "        return images\n",
    "\n",
    "# Create and test the pipeline\n",
    "try:\n",
    "    pipe = SimpleDALIPipeline(batch_size=1, num_threads=2, device_id=0)\n",
    "    pipe.build()\n",
    "    output = pipe.run()\n",
    "\n",
    "    # Get the output as a NumPy array\n",
    "    images = output[0].as_cpu().as_array()\n",
    "    print(f\"DALI is working correctly. Output image shape: {images.shape}\")\n",
    "except Exception as e:\n",
    "    print(f\"DALI test failed. Error: {e}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
